# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      _GH_LIBNX_DIR: ./libnx
      _GH_AWOO_DIR: ./awoo
    container: devkitpro/devkita64:latest
  
    steps:

      - name: Find latest libnx release tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: switchbrew/libnx
          releases-only: true
        id: libnxtag

      - name: Get latest libnx
        uses: actions/checkout@v2
        with:
          repository: switchbrew/libnx
          ref: ${{ steps.libnxtag.outputs.tag }}
        working-directory: env._GH_LIBNX_DIR

      - name: Install libnx
        working-directory: env._GH_LIBNX_DIR
        run: make install

      # Checks-out your repository
      - uses: actions/checkout@v2
        working-directory: env._GH_AWOO_DIR
        with:
          submodules: recursive

      - name: Make
        working-directory: env._GH_AWOO_DIR
        run: make
          
      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Awoo-libnx-${{ steps.libnxtag.outputs.tag }}
          path: ./*.nro
        working-directory: env._GH_AWOO_DIR
