name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      _gh_libnx_dir: ./libnx
      _gh_homebrew_dir: ./homebrew
    container: devkitpro/devkita64:latest
  
    steps:
       - name: Update GIT on Debian Stetch used for devkita64
         run: |
           echo 'deb http://deb.debian.org/debian buster-backports main' >> /etc/apt/sources.list
           apt update
           yes|apt upgrade git
#      - name: Find latest libnx release tag
#        uses: oprypin/find-latest-tag@v1
#        with:
#          repository: switchbrew/libnx
#          releases-only: true
#        id: libnxtag
#
#      - name: Get latest libnx
#        uses: actions/checkout@v2
#        with:
#          path: ${{ env._gh_libnx_dir }}
#          repository: switchbrew/libnx
#          ref: ${{ steps.libnxtag.outputs.tag }}
#
#      - name: Install libnx
#        working-directory: ${{ env._gh_libnx_dir }}
#        run: make install

      # Checks-out your repository
      - name: Checkout this repo
        uses: actions/checkout@v2
        with:
          path: ${{ env._gh_homebrew_dir }}
# TODO: Uncomment and remove redundant dependencies once devkitpro/devkita64 image receives GIT v2.18+
          submodules: true

      - name: Make
        working-directory: ${{ env._gh_homebrew_dir }}
        run: make
          
      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: homebrew-libnx-${{ steps.libnxtag.outputs.tag }}
          path: ${{ env._gh_homebrew_dir }}/*.nro
